# Image neeeds to have ssh-client
image: alpine:3.7

stages:
  - deploy

deploy_dev:
  stage: deploy
  tags:
    - deploy
  only:
    - develop
  script:
    - /home/gitlab-runner/gitlab-ci/lend/develop/lend.sh bribe
    